apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert -o kubernetes/
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: sidekiq
  name: sidekiq
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: sidekiq
    spec:
      containers:
      - envFrom:
        - configMapRef:
           name: special-config1
        image: sidekiq
        name: sidekiq
        imagePullPolicy: IfNotPresent
        resources: {}
      restartPolicy: Always
status: {}
